- aws_lambda_events/src/encodings.rs
Fixes #2. It's not the best interface in the world, but this at least makes the data accessible.
A better solution would be to get rid of these types entirely and just insert the appropriate `{de,}serialize_with` annotations on the generated struct fields themselves. I started down that road, but afaict it's blocked on serde-rs/serde#723 due to the nested types in the SQS structs.
> Make inner fields of encoded data public

- aws_lambda_events/src/generated/README.md
- aws_lambda_events/src/generated/apigw.rs
- aws_lambda_events/src/generated/appsync.rs
- aws_lambda_events/src/generated/autoscaling.rs
- aws_lambda_events/src/generated/cloudwatch_events.rs
- aws_lambda_events/src/generated/sns.rs
- aws_lambda_events_codegen/go_to_rust/src/lib.rs
- aws_lambda_events_codegen/go_to_rust/tests/fixtures/struct_members/expected.txt
This allows callers to provide a struct type for the CloudWatchEvent `detail` field and have it automatically deserialised by the runtime.
As an example, here is the skeleton of a lambda I built to receive CloudWatch Events for STS AssumeRole. Previously you’d write this:
```
lambda::start(|input: CloudWatchEvent| {
let assume_role: AssumeRoleDetail = serde_json::value::from_value(input.detail)?;
...
})
```
Now you can write:
```
lambda::start(|input: CloudWatchEvent<AssumeRoleDetail>| {
...
})
```
I don’t know of any authoritative source for the detail payloads that we could use to codegen them, but this will let you sub in a specific event in place of the `serde_json::Value` field type.
Fixes https://github.com/srijs/rust-aws-lambda/issues/10
<details>
<summary>struct types for …
> Codegen type parameters for serde_json::Value fields

- aws_lambda_events/src/generated/README.md
- aws_lambda_events/src/generated/apigw.rs
- aws_lambda_events/src/generated/code_commit.rs
- aws_lambda_events/src/generated/cognito.rs
- aws_lambda_events_codegen/go_to_rust/src/lib.rs
While developing custom authorizer for lambda API gateway I found that some field names don't match [AWS docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-use-lambda-authorizer.html#api-gateway-lambda-authorizer-token-control-lambda-function). 
It looks like `aws-lambda-go` has correct field name. I've tried to adjust parsing logic so that original field names are kept as is.
> keep original field names for structs

- aws_lambda_events/src/encodings.rs
To improve usability of these single-field tuple types, implement `Deref` and `DerefMut` for these types to make their use more transparent to end-users.
Rather than this:
```rust
let data = Base64Data(Vec::new());
let len = data.0.len();
```
`Deref` makes it possible to skip a step:
```rust
let data = Base64Data(Vec::new());
let len = data.len();
```
> Implement Deref, DerefMut for Encoding Tuple Types

- aws_lambda_events/src/custom_serde.rs
- aws_lambda_events/src/encodings.rs
- aws_lambda_events/src/generated/README.md
- aws_lambda_events/src/generated/apigw.rs
- aws_lambda_events/src/generated/chime_bot.rs
- aws_lambda_events/src/generated/cloudwatch_logs.rs
- aws_lambda_events/src/generated/code_commit.rs
- aws_lambda_events/src/generated/codebuild.rs
- aws_lambda_events/src/generated/codedeploy.rs
- aws_lambda_events/src/generated/cognito.rs
- aws_lambda_events/src/generated/firehose.rs
- aws_lambda_events/src/generated/fixtures/example-firehose-event.json
- aws_lambda_events/src/generated/lex.rs
- aws_lambda_events/src/generated/mod.rs
- aws_lambda_events/src/generated/s3.rs
- aws_lambda_events/src/generated/s3_batch_job.rs
- aws_lambda_events/src/generated/ses.rs
- aws_lambda_events_codegen/go_to_rust/src/lib.rs
- aws_lambda_events_codegen/src/main.rs
Closes https://github.com/LegNeato/aws-lambda-events/issues/12.
For `aws-lambda-go` v1.16.0 with https://github.com/aws/aws-lambda-go/pull/274 a structure `APIGatewayV2HTTPRequestContext` was added with nested struct definitions which Rust does not support and this code generator cannot handle.
I can open an issue in https://github.com/aws/aws-lambda-go pointing this out and asking for all structs to be defined at the top level.
> Fix codegen for aws-lambda-go <= v1.15.0

- aws_lambda_events/src/generated/README.md
- aws_lambda_events/src/generated/apigw.rs
Following the merge of https://github.com/aws/aws-lambda-go/pull/278 we can now generate from https://github.com/aws/aws-lambda-go/commit/7836caa89f2af8a0b81509524bc5b03e1a006e10 and include the additions for [v1.16.0](https://github.com/aws/aws-lambda-go/releases/tag/v1.16.0).
> Generate from upstream v1.16.0

- aws_lambda_events/src/generated/README.md
- aws_lambda_events/src/generated/apigw.rs
Generate from https://github.com/aws/aws-lambda-go/commit/ba3152827fb20751d929ecbc5582af9616d688aa.
Closes https://github.com/LegNeato/aws-lambda-events/issues/17.
> API Gateway v2 fixes from latest upstream aws-lambda-go

- aws_lambda_events/src/generated/README.md
- aws_lambda_events/src/generated/apigw.rs
- aws_lambda_events/src/generated/codebuild.rs
- aws_lambda_events/src/generated/fixtures/example-kafka-event.json
- aws_lambda_events/src/generated/kafka.rs
- aws_lambda_events/src/generated/mod.rs
- aws_lambda_events/src/generated/sns.rs
This is the result of me running the codegen locally with the latest `aws-lambda-go` definitions and checking the diff in.
In particular, I'm interested in this solving: https://github.com/LegNeato/aws-lambda-events/issues/25, but there are many more changes included.
> Catchup with current version of aws-lambda-go

- aws_lambda_events/src/generated/apigw.rs
- aws_lambda_events/src/generated/appsync.rs
- aws_lambda_events/src/generated/cloudwatch_events.rs
- aws_lambda_events_codegen/go_to_rust/src/lib.rs
- aws_lambda_events_codegen/go_to_rust/tests/fixtures/struct_members/expected.txt
- aws_lambda_events_codegen/go_to_rust/tests/fixtures/struct_optional_interface_members/expected.txt
- aws_lambda_events_codegen/go_to_rust/tests/fixtures/struct_optional_interface_members/input.txt
`interface{}` types can be null, and Lambda sends null objects for those in some cases, like websocket requests. This makes the translated objects optional, so the events are still parsed correctly.
Fixes #27
When this is merged, #26 can be closed since this is a general implementation of that.
> Make bounded Go interfaces optional.

- aws_lambda_events/src/custom_serde.rs
- aws_lambda_events/src/generated/README.md
- aws_lambda_events/src/generated/apigw.rs
- aws_lambda_events/src/generated/cognito.rs
- aws_lambda_events/src/generated/lex.rs
- aws_lambda_events_codegen/go_to_rust/src/lib.rs
- aws_lambda_events_codegen/go_to_rust/tests/fixtures/struct_with_http_fields/expected.txt
- aws_lambda_events_codegen/go_to_rust/tests/fixtures/struct_with_http_fields/input.txt
@LegNeato I made some adjustments to properly serialize and deserialize the optional method. The code should still work correctly after the Go bindings are fixed, but we can also retouch this patch then.
Fixes #33 
> Make the http method in the Websocket request struct optional.

- aws_lambda_events/src/custom_serde.rs
- aws_lambda_events_codegen/go_to_rust/src/lib.rs
- aws_lambda_events_codegen/go_to_rust/tests/fixtures/struct_with_http_fields/expected.txt
The Go SDK typically has `omitEmpty` for Rust's `http::HeaderMap` entries, and services like ALB omit them when they're not present. However, without a `default` parameter to the `#[serde()]` annotation, deserialization fails when they're missing instead of the desired behavior of producing an empty `HeaderMap`.
This changes `#[serde(deserialize_with = "http_serde::header_map::deserialize")]` annotations to `#[serde(deserialize_with = "http_serde::header_map::deserialize", default)]` so we get the desired behavior. A test is also added (in `aws_lambda_events/src/custom_serde.rs` -- feel free to suggest a better place if there is one) to verify the correctness of this change.
> Add default to http_serde::header_map::deserialize

- aws_lambda_events_codegen/src/main.rs
We don't need this because it now matches our standard location logic
> Remove override entirely.

- aws_lambda_events/src/generated/apigw.rs
- aws_lambda_events_codegen/go_to_rust/src/lib.rs
> Make ApiGatewayV2httpRequestContext#authentication optional.

- aws_lambda_events/src/generated/alb.rs
- aws_lambda_events/src/generated/apigw.rs
- aws_lambda_events/src/generated/fixtures/alb-lambda-target-request-headers-only.json
- aws_lambda_events/src/generated/fixtures/alb-lambda-target-request-multivalue-headers.json
- aws_lambda_events/src/generated/fixtures/alb-lambda-target-response.json
- aws_lambda_events_codegen/go_to_rust/src/lib.rs
- aws_lambda_events_codegen/src/main.rs
This also brings some tests for ALB because I wasn't sure where this probably was.
Fixes #48 
> Fix undefined field httpMethod.

- aws_lambda_events/src/apigw/mod.rs
- aws_lambda_events_codegen/src/main.rs
Some fields in apigw request and response structs accept
generic arguments, but they were not propagated.
Fix incorrect generic argument in some responses.
Fixes #13 
> Propagate generics between structs

- aws_lambda_events/src/custom_serde/float_unix_epoch.rs
- aws_lambda_events/src/custom_serde/mod.rs
- aws_lambda_events/src/dynamodb/mod.rs
I'm carrying #70 over, so we can do a patch release, @Miaxos
> Carry dynamodb fix

- aws_lambda_events/src/cloudwatch_events/cloudtrail.rs
Almost forgot about this one 😅.
Reference: https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-event-reference-record-contents.html
> chore(cloudwatch): Add additional_event_data to CloudTrail

- aws_lambda_events/src/apigw/mod.rs
The field is only set if using mTLS. See https://aws.amazon.com/blogs/compute/introducing-mutual-tls-authentication-for-amazon-api-gateway/
> For Lambda authorizers, the event payload is expanded to include additional certificate properties from the client’s authenticated certificate. These properties are found at requestContext.identity.clientCert with the Lambda authorizer v1 payload version or at requestContext.authentication.clientCert with the v2 payload version.
> Api gateway: Make client_cert optional

- aws_lambda_events/src/apigw/mod.rs
The identity field is not always given. At least this is the case if just `curl`ing an api gateway with a custom authorizer in Serverless Framework.
This matches https://github.com/LegNeato/aws-lambda-events/blob/9d44e2dab8aba85f33d13cdadc7439bbe1fae10b/aws_lambda_events/src/apigw/mod.rs#L419 and https://github.com/LegNeato/aws-lambda-events/blob/9d44e2dab8aba85f33d13cdadc7439bbe1fae10b/aws_lambda_events/src/apigw/mod.rs#L103
> ApiGW: fix requestcontext.identity being optional

- aws_lambda_events/src/dynamodb/mod.rs
@calavera [as requested](https://github.com/LegNeato/aws-lambda-events/issues/84#issuecomment-1112629718), here's the PR!
Closes #84.
> fix(dynamodb): Make `eventSource`, `eventVersion`, and `eventSourceARN` optional

- aws_lambda_events/Cargo.toml
- aws_lambda_events/src/apigw/mod.rs
API GW V1 and V2 deserialize URL queries in different ways.
QueryMap includes two deserializers to fix this problem.
@adriandelgado this should fix the problem you bumped into.
> Fix issue deserializing url queries.

- aws_lambda_events/src/cloudwatch_events/cloudtrail.rs
`response_elements` is only set if the underlying API call is successful.
> fix(aws_lambda_events): Mark response_elements optional 

- aws_lambda_events/src/cloudwatch_events/cloudtrail.rs
Session context is presumably only available if a role is assumed.
> fix(aws_lambda_events): Mark session_context optional for CloudTrail

- aws_lambda_events/src/generated/fixtures/example-sns-event.json
- aws_lambda_events/src/sns/mod.rs
`Subject` and `MessageAttributes` may be completely missing from the payload.
Additionally `SigningCertURL` and `UnsubscribeURL` have fully capitalized `URL` unlike default renaming from serde of `Url`.
Examples for reference from the official .NET SDK.
https://github.com/aws/aws-sdk-net/blob/475822dec5e87954b7a47ac65995714ae1f1b115/sdk/test/Services/SimpleNotificationService/UnitTests/Custom/SNSMessageUtilityTests.cs#L26-L38
https://github.com/aws/aws-sdk-net/blob/449bb72eccfe78c2bfbd8ee2edbc2a7225e8323b/sdk/src/Services/SimpleNotificationService/Custom/Util/Message.cs#L73-L84
> fix(sns): Properly handle non-required fields, and correct casing.
